<?php

namespace Aura\Notifications\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class SystemUpdateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $updates = [
            [
                'version' => '2.5.0',
                'title' => 'Major Performance Improvements',
                'slug' => 'major-performance-improvements',
                'body' => "We're excited to announce significant performance improvements in this release. Database query optimization reduced load times by 40%, and we've implemented advanced caching mechanisms. Your application will feel noticeably snappier!",
                'category' => 'release',
                'is_pinned' => true,
                'is_published' => true,
                'published_at' => now()->subDays(1),
            ],
            [
                'version' => '2.4.2',
                'title' => 'Security Patch - Critical Update',
                'slug' => 'security-patch-critical-update',
                'body' => 'This release addresses a critical security vulnerability. We strongly recommend updating immediately. The patch fixes a potential XSS vulnerability in user-generated content.',
                'category' => 'maintenance',
                'is_pinned' => true,
                'is_published' => true,
                'published_at' => now()->subDays(3),
            ],
            [
                'version' => '2.4.1',
                'title' => 'Bug Fixes and Stability Improvements',
                'slug' => 'bug-fixes-stability-improvements-2-4-1',
                'body' => 'Fixed several bugs reported by the community including file upload issues, notification delivery problems, and edge cases in the search functionality.',
                'category' => 'maintenance',
                'is_pinned' => false,
                'is_published' => true,
                'published_at' => now()->subDays(7),
            ],
            [
                'version' => '2.4.0',
                'title' => 'New Dashboard Widgets Released',
                'slug' => 'new-dashboard-widgets-released',
                'body' => 'Introducing 5 new customizable dashboard widgets: Analytics Chart, Recent Activity Feed, Quick Stats, Team Performance, and Resource Usage Monitor. Drag and drop to arrange them!',
                'category' => 'release',
                'is_pinned' => false,
                'is_published' => true,
                'published_at' => now()->subDays(14),
            ],
            [
                'version' => '2.3.5',
                'title' => 'Enhanced Search Functionality',
                'slug' => 'enhanced-search-functionality',
                'body' => 'Search is now 3x faster with support for fuzzy matching, filters, and advanced operators. You can now search across multiple resource types simultaneously.',
                'category' => 'release',
                'is_pinned' => false,
                'is_published' => true,
                'published_at' => now()->subDays(21),
            ],
            [
                'version' => '2.3.4',
                'title' => 'Scheduled Maintenance - January 20th',
                'slug' => 'scheduled-maintenance-january-20th',
                'body' => 'We will be performing scheduled maintenance on January 20th from 2:00 AM to 4:00 AM UTC. The system will be unavailable during this time. Thank you for your patience!',
                'category' => 'announcement',
                'is_pinned' => false,
                'is_published' => true,
                'published_at' => now()->subDays(28),
            ],
            [
                'version' => '2.3.3',
                'title' => 'API Rate Limiting Introduced',
                'slug' => 'api-rate-limiting-introduced',
                'body' => 'To ensure fair usage and system stability, we\'ve introduced rate limiting on API endpoints. Free tier: 1000 requests/hour, Pro tier: 10000 requests/hour.',
                'category' => 'announcement',
                'is_pinned' => false,
                'is_published' => true,
                'published_at' => now()->subDays(35),
            ],
            [
                'version' => '2.3.0',
                'title' => 'Multi-language Support',
                'slug' => 'multi-language-support',
                'body' => 'Aura CMS now supports 15 languages! Easily switch between languages in your profile settings. We support English, Spanish, French, German, Italian, Portuguese, and more.',
                'category' => 'release',
                'is_pinned' => false,
                'is_published' => true,
                'published_at' => now()->subDays(42),
            ],
            [
                'version' => '2.2.8',
                'title' => 'Export Functionality Enhanced',
                'slug' => 'export-functionality-enhanced',
                'body' => 'You can now export your data in CSV, Excel, JSON, and PDF formats. Scheduled exports are also available for automated reporting.',
                'category' => 'release',
                'is_pinned' => false,
                'is_published' => true,
                'published_at' => now()->subDays(49),
            ],
            [
                'version' => '2.2.5',
                'title' => 'Dark Mode Released',
                'slug' => 'dark-mode-released',
                'body' => 'The most requested feature is here! Toggle dark mode in your profile settings for a comfortable viewing experience during late-night work sessions.',
                'category' => 'release',
                'is_pinned' => false,
                'is_published' => true,
                'published_at' => now()->subDays(56),
            ],
            [
                'version' => '2.2.0',
                'title' => 'Real-time Collaboration Features',
                'slug' => 'real-time-collaboration-features',
                'body' => 'Work together in real-time! See who\'s viewing or editing resources, get instant notifications when changes are made, and use the new comment system for team communication.',
                'category' => 'release',
                'is_pinned' => false,
                'is_published' => true,
                'published_at' => now()->subDays(63),
            ],
            [
                'version' => '2.1.5',
                'title' => 'Mobile App Beta Launch',
                'slug' => 'mobile-app-beta-launch',
                'body' => 'Our mobile app is now in beta! Download for iOS and Android to manage your resources on the go. Push notifications keep you updated wherever you are.',
                'category' => 'announcement',
                'is_pinned' => false,
                'is_published' => true,
                'published_at' => now()->subDays(70),
            ],
            [
                'version' => '2.1.0',
                'title' => 'Advanced Permissions System',
                'slug' => 'advanced-permissions-system',
                'body' => 'Granular control over user permissions! Create custom roles, assign specific permissions to resources, and manage team access with precision.',
                'category' => 'release',
                'is_pinned' => false,
                'is_published' => true,
                'published_at' => now()->subDays(77),
            ],
            [
                'version' => '2.0.0',
                'title' => 'Aura CMS 2.0 - Complete Redesign',
                'slug' => 'aura-cms-2-0-complete-redesign',
                'body' => 'Welcome to Aura CMS 2.0! Completely redesigned interface, rebuilt on Laravel 11, improved performance, new field types, advanced widgets, and so much more. This is our biggest update yet!',
                'category' => 'release',
                'is_pinned' => false,
                'is_published' => true,
                'published_at' => now()->subDays(84),
            ],
            [
                'version' => '1.9.8',
                'title' => 'Two-Factor Authentication',
                'slug' => 'two-factor-authentication',
                'body' => 'Secure your account with two-factor authentication! Support for authenticator apps, SMS codes, and backup codes. Enable it in your security settings today.',
                'category' => 'release',
                'is_pinned' => false,
                'is_published' => true,
                'published_at' => now()->subDays(91),
            ],
            [
                'version' => '1.9.5',
                'title' => 'Automated Backups',
                'slug' => 'automated-backups',
                'body' => 'Never lose your data! Automated daily backups are now enabled for all accounts. Restore to any point in time with one click.',
                'category' => 'release',
                'is_pinned' => false,
                'is_published' => true,
                'published_at' => now()->subDays(98),
            ],
            [
                'version' => '1.9.0',
                'title' => 'API Documentation Portal',
                'slug' => 'api-documentation-portal',
                'body' => 'Comprehensive API documentation is now available at docs.aura-cms.com. Interactive examples, code snippets, and postman collections included.',
                'category' => 'announcement',
                'is_pinned' => false,
                'is_published' => true,
                'published_at' => now()->subDays(105),
            ],
            [
                'version' => '1.8.5',
                'title' => 'Webhook Support',
                'slug' => 'webhook-support',
                'body' => 'Integrate with external services using webhooks! Get real-time notifications when resources are created, updated, or deleted.',
                'category' => 'release',
                'is_pinned' => false,
                'is_published' => true,
                'published_at' => now()->subDays(112),
            ],
            [
                'version' => '1.8.0',
                'title' => 'Custom Field Types',
                'slug' => 'custom-field-types',
                'body' => 'Create your own field types! Extend Aura CMS with custom fields tailored to your specific needs. Full documentation and examples provided.',
                'category' => 'release',
                'is_pinned' => false,
                'is_published' => true,
                'published_at' => now()->subDays(119),
            ],
            [
                'version' => '1.7.5',
                'title' => 'Upcoming Feature: AI-Powered Search',
                'slug' => 'upcoming-feature-ai-powered-search',
                'body' => 'Coming soon: AI-powered semantic search that understands context and intent. Beta testing starts next month. Sign up for early access!',
                'category' => 'announcement',
                'is_pinned' => false,
                'is_published' => false,
                'published_at' => null,
            ],
        ];

        foreach ($updates as $update) {
            DB::table('aura_system_updates')->insert([
                'team_id' => 1,
                'user_id' => 1,
                'version' => $update['version'],
                'title' => $update['title'],
                'slug' => $update['slug'],
                'body' => $update['body'],
                'category' => $update['category'],
                'tags' => json_encode([]),
                'published_at' => $update['published_at'],
                'created_by' => 1,
                'is_pinned' => $update['is_pinned'],
                'is_published' => $update['is_published'],
                'created_at' => $update['published_at'] ?? now(),
                'updated_at' => $update['published_at'] ?? now(),
            ]);
        }

        $this->command->info('✓ Created 20 system updates successfully!');
    }
}
